### ISSUE TITLE
.travis.yml references an EOL node version

### ISSUE THREAD

**Issue by dominykas** [nodejs/security-advisories#16]
I was going through `.travis.yml` across the org to look for outdated Node.js versions and spotted this repo referencing `8.9.0`. I figure it needs a bump?

Not sure what this is used for - is it meant to be testing in a single version? If so - might make sense to just change the version to `lts/*` or `latest`. If it's meant to test in multiple versions - it may be worth using one of the shared configs at https://github.com/nodejs/ci-config-travis to automatically include new versions?

Happy to PR, if needed.

**Comment by DanielRuf** [comment]
Thanks for the hint.

It seems the builds fail: https://github.com/nodejs/security-advisories/runs/1048096722 which syncs the repo at github.com/nodejs/security-advisories using https://github.com/nodejs/security-advisories/blob/master/travis/sync.sh and validates the advisories.

See also https://travis-ci.com/github/nodejs/security-advisories/builds/181961332.
I doubt that the Node version is really security relevant as we sync and validate only the advisories.

Not sure since when it fails (have to check the action / commit history).

If it works with the latest stable / LTS version locally we can switch to the proposed one.

**Comment by DanielRuf** [comment]
Thanks for the hint.

It seems the builds fail: https://github.com/nodejs/security-advisories/runs/1048096722 which syncs the repo at github.com/nodejs/security-advisories using https://github.com/nodejs/security-advisories/blob/master/travis/sync.sh and validates the advisories.

See also https://travis-ci.com/github/nodejs/security-advisories/builds/181961332.
I doubt that the Node version is really security relevant as we sync and validate only the advisories.

Not sure since when it fails (have to check the action / commit history).

If it works with the latest stable / LTS version locally we can switch to the proposed one. A PR would be great.

**Comment by Trott** [comment]
I've unarchived this repo so I can close all PRs and issues before re-archiving.
